export const categories = {
  income: { id: 1 },
  saving: { id: 2 },
  gifts: { id: 3 },
  housing: { id: 4 },
  utilities: { id: 5 },
  food: { id: 6 },
  transportation: { id: 7 },
  health: { id: 8 },
  dailyLiving: { id: 9 },
  children: { id: 10 },
  obligation: { id: 11 },
  entertainment: { id: 12 },
  other: { id: 13 },
  balanceAdjust: { id: 14 },
  transfer: { id: 15 },
} as const;

export const categoryTypes = {
  income_wage: { id: 1, categoryId: 1 },
  income_interests: { id: 2, categoryId: 1 },
  income_gifts: { id: 3, categoryId: 1 },
  income_refunds: { id: 4, categoryId: 1 },
  income_financial_aid: { id: 5, categoryId: 1 },
  income_other: { id: 6, categoryId: 1 },
  saving_emergency: { id: 7, categoryId: 2 },
  saving_retirement: { id: 8, categoryId: 2 },
  saving_vacation: { id: 9, categoryId: 2 },
  saving_others: { id: 10, categoryId: 2 },
  charity_donations: { id: 11, categoryId: 3 },
  gifts: { id: 12, categoryId: 3 },
  charity_other: { id: 13, categoryId: 3 },
  mortgage_rent: { id: 14, categoryId: 4 },
  housing_improvements: { id: 15, categoryId: 4 },
  housing_supplies: { id: 16, categoryId: 4 },
  housing_other: { id: 17, categoryId: 4 },
  utilities_electricity: { id: 18, categoryId: 5 },
  utilities_gas_oil: { id: 19, categoryId: 5 },
  utilities_water_sewer_trash: { id: 20, categoryId: 5 },
  utilities_phone: { id: 21, categoryId: 5 },
  utilities_cable_satellite: { id: 22, categoryId: 5 },
  utilities_internet: { id: 23, categoryId: 5 },
  utilities_other: { id: 24, categoryId: 5 },
  food_groceries: { id: 25, categoryId: 6 },
  food_eating_out: { id: 26, categoryId: 6 },
  food_other: { id: 27, categoryId: 6 },
  transportation_insurance: { id: 28, categoryId: 7 },
  transportation_payments: { id: 29, categoryId: 7 },
  transportation_fuel: { id: 30, categoryId: 7 },
  transportation_ticket: { id: 31, categoryId: 7 },
  transportation_taxi: { id: 32, categoryId: 7 },
  transportation_repairs: { id: 33, categoryId: 7 },
  transportation_registration: { id: 34, categoryId: 7 },
  transportation_other: { id: 35, categoryId: 7 },
  health_insurance: { id: 36, categoryId: 8 },
  health_doctor: { id: 37, categoryId: 8 },
  health_medicine: { id: 38, categoryId: 8 },
  health_other: { id: 39, categoryId: 8 },
  dailyLiving_education: { id: 40, categoryId: 9 },
  dailyLiving_clothing: { id: 41, categoryId: 9 },
  dailyLiving_personal: { id: 42, categoryId: 9 },
  dailyLiving_cleaning: { id: 43, categoryId: 9 },
  dailyLiving_salon_barber: { id: 44, categoryId: 9 },
  dailyLiving_other: { id: 45, categoryId: 9 },
  children_clothing: { id: 46, categoryId: 10 },
  children_medical: { id: 47, categoryId: 10 },
  children_school: { id: 48, categoryId: 10 },
  children_babysitting: { id: 49, categoryId: 10 },
  children_toys_games: { id: 50, categoryId: 10 },
  children_other: { id: 51, categoryId: 10 },
  obligation_loan: { id: 52, categoryId: 11 },
  obligation_credit_card: { id: 53, categoryId: 11 },
  obligation_child_support: { id: 54, categoryId: 11 },
  obligation_taxes: { id: 55, categoryId: 11 },
  obligation_other: { id: 56, categoryId: 11 },
  entertainment_vacation_travel: { id: 57, categoryId: 12 },
  entertainment_movies: { id: 58, categoryId: 12 },
  entertainment_music: { id: 59, categoryId: 12 },
  entertainment_games: { id: 60, categoryId: 12 },
  entertainment_rental: { id: 61, categoryId: 12 },
  entertainment_books: { id: 62, categoryId: 12 },
  entertainment_hobbies: { id: 63, categoryId: 12 },
  entertainment_sport: { id: 64, categoryId: 12 },
  entertainment_gadgets: { id: 65, categoryId: 12 },
  entertainment_other: { id: 66, categoryId: 12 },
  expenses_other: { id: 67, categoryId: 13 },
  balanceAdjust: { id: 68, categoryId: 14 },
  transfer_send: { id: 69, categoryId: 15 },
  transfer_received: { id: 70, categoryId: 15 },
} as const;
